name: CI/CD Pipeline

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

permissions:
  checks: write
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "8.0.x"

      - name: Run linters
        uses: wearerequired/lint-action@v2
        with:
          dotnet_format: true
      
      - name: dotnet-format
        uses: xt0rted/dotnet-format@v1.2.0
      
