name: CI/CD Pipeline

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build project
        run: dotnet build
      - name: Format code
        uses: eero-dev/dotnet-format@1.0.1 --workspace proy_caguamanta.sln
      - name: Linting Action
        uses: ryanclark/lint-action@v1.15.0
